### ISSUE TITLE
client 启动netty时EventLoopGroup核心线程数为什么设置成0

### ISSUE THREAD

**Issue by kevindai007** [crossoverJie/cim#113]
```
public class KimClient {
    private EventLoopGroup group = new NioEventLoopGroup(0, new DefaultThreadFactory("cim-work"));
    //........
}
```

**Comment by crossoverJie** [comment]
![image](https://user-images.githubusercontent.com/15684156/99343258-79627d00-28c8-11eb-8a1c-382843238e11.png)
![image](https://user-images.githubusercontent.com/15684156/99343739-7451fd80-28c9-11eb-9185-fe0fd3f02aa2.png)


设置为0会根据操作系统配置来调整线程数。
