### ISSUE TITLE
服务节点集群部署，hash算法选择节点时bug

### ISSUE THREAD

**Issue by 139446702556** [crossoverJie/cim#116]
SortArrayMapConsistentHash：
public void add(long key, String value) {
        // fix https://github.com/crossoverJie/cim/issues/79
        sortArrayMap.clear();
        for (int i = 0; i < VIRTUAL_NODE_SIZE; i++) {
            Long hash = super.hash("vir" + key + i);
            sortArrayMap.add(hash,value);
        }
        sortArrayMap.add(key, value);
    }
TreeMapConsistentHash：
public void add(long key, String value) {

        // fix https://github.com/crossoverJie/cim/issues/79
        treeMap.clear();
        for (int i = 0; i < VIRTUAL_NODE_SIZE; i++) {
            Long hash = super.hash("vir" + key + i);
            treeMap.put(hash,value);
        }
        treeMap.put(key, value);
    }

master分支上的这两个hash的存储方式的add方法会导致集群部署时，始终只会从最后一个节点中的三个虚拟节点选择，而其他节点都被clear掉了

**Comment by alun2kb** [comment]
哇，刚好在尝试部署多台 server，感谢指出避坑！
