### ISSUE TITLE
支持表情包吗

### ISSUE THREAD

**Issue by kakisong** [crossoverJie/cim#12]
哈哈哈哈哈，我无处安放的表情包

**Comment by crossoverJie** [comment]
@kakisong 

哈哈，你可以这样发送支持表情包。

![image](https://user-images.githubusercontent.com/15684156/50676460-683f5880-102f-11e9-8594-d5f21845f844.png)
![image](https://user-images.githubusercontent.com/15684156/50676469-7ab99200-102f-11e9-9c8f-f1ae87f9ef49.png)


https://ws3.sinaimg.cn/large/006tNc79ly1fyujjzpmanj305k05kaa7.jpg

**Comment by 13120241790** [comment]
可以考虑加 emoji unicode 这个比较简单能实现表情 网络传输的时候就是字符串在传输

**Comment by LiMoMoMo** [comment]
> 可以考虑加 emoji unicode 这个比较简单能实现表情 网络传输的时候就是字符串在传输

😂

**Comment by crossoverJie** [comment]
![](https://tva1.sinaimg.cn/large/006y8mN6ly1g6j910cqrzj30dn05qjw9.jpg)

@LiMoMoMo 现已支持。
