### ISSUE TITLE
CHANNEL_MAP 本地存储问题

### ISSUE THREAD

**Issue by hakusai22** [crossoverJie/cim#132]
Map<Long, NioSocketChannel> CHANNEL_MAP = new ConcurrentHashMap<>(16); 用户id和channel在本地进行存储，如果用户的量级过大，出现本地内存太大进行GC,用户关联的信息丢失，用户需要重新创建channel，服务器重启本地缓存channel丢失，请求有什么优化的方案吗？

**Comment by crossoverJie** [comment]
方案挺多的：
- 这个 map 可以持久化到磁盘，当然也有策略，比如只把频繁活跃的 Id 存入，也可以在磁盘和内存中做索引，加快查询速度；这个要做好比较复杂（类似于数据库索引了），应该有现成的库。
- 根据用户量水平扩展 server，让一个节点的 map 数量始终在一个可接受的范围，这个更简单。

**Comment by hakusai22** [comment]
> 

磁盘的话 那还不如直接找张表存进去，能否使用redis的hash数据结构进行优化？
