### ISSUE TITLE
router没有集群

### ISSUE THREAD

**Issue by s949492225** [crossoverJie/cim#14]
router没有集群的话，应该会成为性能瓶颈吧，另外，socket的客户端和服务端都应该有收到消息的回执吧，接受者离线，应该有专门处理离线消息的模块

**Comment by crossoverJie** [comment]
@s949492225 

1. `route` 是无状态的，支持 `Nginx` 反向代理，可以集群部署。
2. 关于消息的送达率在这里有讨论 https://github.com/crossoverJie/cim/issues/9#issuecomment-451044355
3. 离线消息在规划中了。
