### ISSUE TITLE
cim-server模块报红 缺少com.crossoverjie.cim.common.protocol包

### ISSUE THREAD

**Issue by codegod-maker** [crossoverJie/cim#167]
是否是需要编译proto生成代码文件 编译生成步骤是啥
![image](https://github.com/user-attachments/assets/6b1d82cf-a5fe-414f-8a02-ce4c2155a716)
![image](https://github.com/user-attachments/assets/25e08f43-ca7a-4cbe-bd08-ca5433de0491)

**Comment by crossoverJie** [comment]
Execute this command in the project root directory:
```bash
cd cim
mvn clean package -DskipTests=true
```

**Comment by codegod-maker** [comment]
可以了 谢谢
