### ISSUE TITLE
每个netty客户端都需要启动一个web客户端吗?

### ISSUE THREAD

**Issue by zhangxi123** [crossoverJie/cim#18]
cp /cim/cim-client/target/cim-client-1.0.0-SNAPSHOT.jar /xx/work/route0/
cd /xx/work/route0/
java -jar cim-client-1.0.0-SNAPSHOT.jar --server.port=8084 --cim.user.id=唯一客户端ID --cim.user.userName=用户名 --cim.group.route.request.url=http://路由服务器:8083/groupRoute --cim.server.route.request.url=http://路由服务器:8083/login

**Comment by crossoverJie** [comment]
> web客户端吗?

`web` 客户端指 `--server.port=8084` 这个？

----
如果你需要在本地启动多个客户端，只需要修改 `--server.port=8084` 端口即可；

因为在之前的开发阶段需要用 `HTTP` 接口进行调试，后期会评估是否需要去掉 `web` 服务。
