### ISSUE TITLE
提交之前请查看是否有相关 issue，谢谢。

### ISSUE THREAD

**Issue by meiyounameduo05** [crossoverJie/cim#22]
我用本地的idea 

- [启动起来之后postman来发送消息回报错]
![image](https://user-images.githubusercontent.com/32794399/51289901-00303f80-1a3d-11e9-8871-ab14e6865b6a.png)

**Comment by meiyounameduo05** [comment]
启动服务
![image](https://user-images.githubusercontent.com/32794399/51290595-15a66900-1a3f-11e9-8ef3-d75a403319ad.png)
之后用postman 向服务端发消息 
![image](https://user-images.githubusercontent.com/32794399/51290676-5e5e2200-1a3f-11e9-982c-fd9602782075.png)
在cim-server端回报这个错误
![image](https://user-images.githubusercontent.com/32794399/51290753-98c7bf00-1a3f-11e9-8957-d427e9895b78.png)

**Comment by crossoverJie** [comment]
不要直接在客户端向服务端发送消息，所有的消息都得通过 route，后面会把客户端的接口关闭。
