### ISSUE TITLE
CIMRequestProto.CIMReqProtocol or CIMResponseProto.CIMResProtocol

### ISSUE THREAD

**Issue by shoyu666** [crossoverJie/cim#25]
看了下代码，有些不解，请问下：
看了下发送和接收的数据结构的名称不一样
`发送的结构是 CIMRequestProto.CIMReqProtocol`
`接收的结构是 CIMResponseProto.CIMResProtocol`
理论上2进制数据应该是一样 的吧？如果那样，为什么不用一种？还是说在上层做业务区分？
问题比较低级，还望不吝赐教

**Comment by crossoverJie** [comment]
原本是设计的不同的结构，后面做的过程中发现双方的参数都需要于是 `Request` 和 `Response`  的字段就一样了。

现阶段可以认为是一个东西。

**Comment by shoyu666** [comment]
@crossoverJie  谢谢答复
