### ISSUE TITLE
RouteController login方法登录校验成功以后，后续发生的异常时做一下客户端下线或许更好哦～😄

### ISSUE THREAD

**Issue by Askerlve** [crossoverJie/cim#28]
**Bug 描述**
RouteController login方法登录校验成功以后，后续发生的异常时做一下客户端下线或许更好哦～😄

**复现**
复现步骤:
1.单实例启动服务端模块。
2.单实例启动路由模块。
3.单实例启动客户端模块。
4.停止服务端。
5.重新启动客户端，用户校验成功，登录状态入库成功，拉取服务端路由信息抛出异常，客户端启动失败。 
6.重新拉起服务端模块。
7.启动客户端提示“账号重复登录，请退出一个账号!”。

**预期结果**
客户端启动成功！

**截图**
![image](https://user-images.githubusercontent.com/14157567/51974140-313b5600-24ba-11e9-8d95-97cfe859f5c7.png)

**Comment by crossoverJie** [comment]
有两种方案可以解决：

- 登录时需要校验目前可用的服务节点，如果没有则不允许登录，可以从源头杜绝这个问题。
- 第二种就是你说的方案，但这是一种出问题了的迂回策略，我更倾向第一种。

**Comment by Askerlve** [comment]
嗯嗯，大大的赞～

**Comment by crossoverJie** [comment]
@Askerlve 感兴趣可以提个 PR 过来解决这个问题😀

**Comment by crossoverJie** [comment]
![image](https://user-images.githubusercontent.com/15684156/79072029-6b84c200-7d11-11ea-8563-fa9649869b5a.png)

@Askerlve 时隔多年终于是修复了该问题。
