### ISSUE TITLE
关于客户端消息推送

### ISSUE THREAD

**Issue by smallFive55** [crossoverJie/cim#32]
是否会支持客户端发送消息也通过Netty推送呢？
目前好像只是由服务端提供了消息的下发，下游client调用服务端提供的api进行消息发送。

**Comment by crossoverJie** [comment]
这个问题问的人不少，再次统一回复下。

1. `cim` 是支持 `client` 和 `server` 端通过 `TCP` 直接发送消息，只是提供的消息发送 `api` 不是这样实现的而已。
2. 之所以所有的消息都通过 `http` 的 `route` 转发一遍是为了 `server` 端的水平扩展。
3. 如果只是点对点通信或者是单机版那自然可以客户端通过 `netty + TCP` 长连接发送消息（`cim` 在开发初期验证功能时就是这样调试的）。
