### ISSUE TITLE
看到了大佬价值一亿的AI代码

### ISSUE THREAD

**Issue by Sunnus3** [crossoverJie/cim#34]
哈哈

**Comment by Sunnus3** [comment]
有一个大胆的想法,route模块与server模块通过mq来通信

**Comment by crossoverJie** [comment]
并不是什么场景都适合 `MQ`；目前 `route` 和 `server` 的大部分通信都是为了转发消息，作为把`即时通讯`作为标签的应用却把最核心的消息发送换为异步我觉得并不合适。

个人认为 `MQ` 作为进程间通信的一种方式更多的还是为了削峰限流，并不适合目前的场景。

**Comment by Sunnus3** [comment]
也是哦,如果 route 与 server 之间的链接不多的话有点画蛇添足的意思了,但是 route 与 server 之间的链接非常频繁的话,我认为将 http 改成 mq 也未尝不可

**Comment by Sunnus3** [comment]
目前代码发送一条消息的链路是 local client -> route -> server -> remote client 相当于是同步的

**Comment by Sunnus3** [comment]
请问一下大佬,目前搭建的demo环境,server是不是在部署在局域网内或者docker中,route返回的 CimServerRestVO对象中的IP(172.20.16.78)地址是ping不通的

**Comment by crossoverJie** [comment]
多网卡的情况目前没考虑，今后可能会加上内外网映射 IP 的功能，或者是由用户自己配置 server 的 ip 都是可行的。

**Comment by Sunnus3** [comment]
我自己在本地的处理方式是增加一个cim.server.ip的参数,通过AppConfiguration对象获取参数,在get方法中判断,如果不为空直接返回,如果为空通过InetAddress.getLocalHost().getHostAddress()获取

**Comment by crossoverJie** [comment]
嗯，这样也可以，就是说的由用户自己配置那种方案。

**Comment by Sunnus3** [comment]
哈哈,我pr一下吗

**Comment by crossoverJie** [comment]
这个需求还没有完全想好，先等等啊。

**Comment by Sunnus3** [comment]
通过docker运行有注册发现环节的服务时,如果不将网络模式设置为host,大佬目前有比较好的处理方式吗

**Comment by crossoverJie** [comment]
不好意思，docker 我不是很熟。

**Comment by chenghongzhi** [comment]
> 通过docker运行有注册发现环节的服务时,如果不将网络模式设置为host,大佬目前有比较好的处理方式吗

Docker 中通信要么统一采用容器Ip彼此通信，如果为了和宿主机通信的话只能走host模式。和主机共享网络的
