### ISSUE TITLE
消息顺序的问题

### ISSUE THREAD

**Issue by fantasygg** [crossoverJie/cim#35]
你好，我看代码中，并没有专门对消息顺序进行处理，是否有出现消息乱序的可能，在设计时，对这方面是怎么考虑的呢？比如，在http调用的过程中，可能出现的网络延时导致的消息乱序？

**Comment by crossoverJie** [comment]
有这样的可能，比如群聊时有一人网络不好可能会导致他之前发的消息最后才收到。

这样的情况我看微信、QQ 也存在。

我觉得可以在每条消息加上消息生成的时间戳（不是服务器生成的时间有可能会被客户端篡改），然后客户端根据这样来展示；但不清楚微信之类的为啥没有这个功能。

> 不过这样也挺奇怪的，几个人聊着聊着中间突然插入一条消息。

**Comment by fantasygg** [comment]
不好意思。我再详细追问一下：

（说的可能都是极端的情况，不要说我杠精，只是想听一下你对这里的见解，/捂脸）

首先谢谢你的回答，你所说的这种情况下，并没有改变这个人接收到消息的顺序，而且客户端这么处理的话确实很奇怪，哈哈。


发送消息的主要代码:
![image](https://user-images.githubusercontent.com/13445354/53725728-85659b80-3ea7-11e9-8af6-c115b22968d5.png)


![image](https://user-images.githubusercontent.com/13445354/53725546-2f90f380-3ea7-11e9-947c-1fc2f0c270f0.png)

同时有2个成员发送了消息，消息先后到达了这里，因为某个环节网络的原因，可能会导致在某个群聊成员的客户端，就出现了第2条消息先到达的情况，这时这个客户端就出现了消息顺序的错乱。

是不是这种情况也可以不用处理呢，或者说有什么解决方案吗？

可以说一下你对这两块代码可能会出现的网络延迟的理解吗？

**Comment by crossoverJie** [comment]
> 是不是这种情况也可以不用处理呢，或者说有什么解决方案吗？
> 
> 可以说一下你对这两块代码可能会出现的网络延迟的理解吗？

延迟肯定是有可能的，比如 `TCP` 连接不稳定，传输过程中掉包重传之类的，会有这样的可能。

我觉得不用处理，也不好处理。

在同一个 `JVM` 里倒是可以让消息发送后响应 `ACK` 再发送下一条，这样可以满足顺序，但同样会有几个问题：

1. 消息发送吞吐量降低，所有的消息发送都是串行，一个消息响应 `ACK` 较慢就会影响后续的消息。
2. 分布式的情况下还需要借助额外的中间件来保证每条消息的 `ACK`，这样吞吐量又会降低。

所以综上我觉得想要在服务端实现消息顺序代价有点高，即便是 `Kafka` 这样高吞吐量的中间件也是只能保证单个分区的顺序，在 IM 这样的场景本身也没这个必要。

**Comment by fantasygg** [comment]
感谢感谢
