### ISSUE TITLE
客户端服务启动报错

### ISSUE THREAD

**Issue by mark988** [crossoverJie/cim#37]
启动命令：
java -jar /data/app/cim-client-1.0.0-SNAPSHOT.jar --server.port=8084 --cim.user.id=123456 --cim.user.userName=zhangsan --cim.group.route.request.url=http://10.19.151.154:8083/groupRoute --cim.server.route.request.url=http://10.19.151.154:8083/login

**Bug 描述**
启动报错，无法启动client

**截图**
![1](https://user-images.githubusercontent.com/22902512/53948840-af1afe80-4103-11e9-95b0-1458c1cbef84.png)

![2](https://user-images.githubusercontent.com/22902512/53948868-c0640b00-4103-11e9-8a44-4d3ea18c66d2.png)

**Comment by crossoverJie** [comment]
再贴一下客户端报错时 `route` 的日志情况。

**Comment by mark988** [comment]
server route 都启动成功了。但是client 报错如下： 
![4](https://user-images.githubusercontent.com/22902512/54004914-5cd4ee80-4192-11e9-8cb7-587a3c89644d.png)

**Comment by mark988** [comment]
已经启动了。谢谢。
