### ISSUE TITLE
客户端route模块登陆成功,server模块链接失败,此时需手动调用offLine接口清除路由信息才能登陆

### ISSUE THREAD

**Issue by arugal** [crossoverJie/cim#38]
route 服务登陆后返回的 server 服务地址与 client 网络不可达时,server 服务无法通过 tcp 链接的断开触发 offLine 接口清除路由信息

**Comment by crossoverJie** [comment]
> route 服务登陆后返回的 server 服务地址与 client 网络不可达时

是指注册到 Zookeeper 上的地址客户端本身就 ping 不通嘛？

这个只能注册一个可以访问的地址才行。

**Comment by Sunnus3** [comment]
那就是两个问题了
1: 机器多网卡时的ip问题,需要绑定外网地址并注册到 zookeeper 中,这个在 #34 中我有提及
2: 启动client -> route.login (保存路由信息,返回CIMServerResVO) -> server.netty(链接失败, CIMServer 网络不可达或其他原因) -> 退出client(route中仍然保存本次路由信息,需要调用 offLine 手动清除路由信息),
此处是不是需要定时校验一些登陆路由信息的可用性

**Comment by Sunnus3** [comment]
或者说一次登陆是不是需要经过 server 的确认才算完成呢

**Comment by crossoverJie** [comment]
1. 多网卡那个先缓缓。
2. 第二个问题其实在 https://github.com/crossoverJie/cim/issues/28#issuecomment-459176275 有提过，这本身是一个事务操作，只是涉及到了分布式的情况；可以在创建连接的时候 ping 一下是否可用，如果不可用则需要剔除同时重连。

**Comment by crossoverJie** [comment]
> 或者说一次登陆是不是需要经过 server 的确认才算完成呢

https://github.com/crossoverJie/cim/issues/28#issuecomment-612629676  #87 该问题修复了，每次登陆之前都会校验 `server` 是否真的可用，没问题后才会写入路由状态。
