### ISSUE TITLE
crossoverjie 上文章我看不到图片

### ISSUE THREAD

**Issue by xiguizi** [crossoverJie/cim#40]
博主在crossoverjie.top/  文章我看不见图片，请看下。

**Comment by crossoverJie** [comment]
贴下截图。

**Comment by HuangDayu** [comment]
![](https://ws1.sinaimg.cn/large/006eVJXJgy1g2ez39c9mwj30ko0ay757.jpg)

@crossoverJie

**Comment by HuangDayu** [comment]
新浪限制外链了，ws2不行了，ws3还可以。
@crossoverJie 

https://ws2.sinaimg.cn/large/006tNc79gy1fsx4cctol0j30k70dq40n.jpg

https://ws3.sinaimg.cn/large/006tNc79gy1fsx4cctol0j30k70dq40n.jpg

**Comment by crossoverJie** [comment]
应该是微博服务的问题，我这里也时好时坏，影响阅读可以查看公众号。
