### ISSUE TITLE
客户端重连只是根据心跳来进行判断对吧？

### ISSUE THREAD

**Issue by buildupchao** [crossoverJie/cim#44]
客户端重连只是根据心跳来进行判断对吧？

**Comment by crossoverJie** [comment]
1. 客户端发送的心跳是为了保证不被服务端剔除下线。
2. 客户端重连的触发条件是发生通道关闭，具体见以下代码。

https://github.com/crossoverJie/cim/blob/3ae7d952a4584e0b6fa772cce61cc1556e346342/cim-client/src/main/java/com/crossoverjie/cim/client/handle/CIMClientHandle.java#L92

**Comment by sdisk** [comment]
如果出现网络异常的情况，这种客户端发送心跳包到服务端保持心跳是不行的吧？

**Comment by crossoverJie** [comment]
> 如果出现网络异常的情况，这种客户端发送心跳包到服务端保持心跳是不行的吧？

服务端如果迟迟没有收到客户端心跳也会主动将客户端踢下线。
