### ISSUE TITLE
请教一个问题，netty 怎么实现同时处理 java 客户端的 tcp 连接 和 js 端的Websocket 连接

### ISSUE THREAD

**Issue by lmxdawn** [crossoverJie/cim#46]
实现的功能就是 js 端 websocket 连接用于接收消息，发送消息通过 http 请求到 java 提供的服务，然后这个 java 服务推送 消息到 websocket 上面，所以就需要 netty 启用的 服务既 支持 java 写的客户端 tcp 连接 又 支持 js 前端的 websocket 连接

这里有部分代码，但是没有实现这个功能：[https://github.com/lmxdawn/netty-demo/tree/master/src/main/java/com/example/nettydemo/websocket3](https://github.com/lmxdawn/netty-demo/tree/master/src/main/java/com/example/nettydemo/websocket3)

**Comment by crossoverJie** [comment]
理论上是可以的，在收到消息后判断消息报文是符合自定义的 `tcp` 协议，还是满足 `websocket` 协议；然后再做不同的处理。

可以参考这个试试：

https://github.com/ordiychen/netty-protocol-dispacher/blob/9db9c19e11ea3a9b3d1a03b32430c41c3b83457a/src/main/java/my/ordiy/git/proter/MsgInboundFilter.java#L46-L67

**Comment by lmxdawn** [comment]
好的，感谢
