### ISSUE TITLE
提交之前请查看是否有相关 issue，谢谢。

### ISSUE THREAD

**Issue by LUCKYZHOUSTAR** [crossoverJie/cim#48]
**Bug 描述**
A用户登录后，获取到的是Bserver的地址，连接的是Bserver
C用户登录后，获取到的是Dserver的地址，连接的是Dserver
此时A用户向C用户发送消息的话，Bserver上转发消息时，找不到C用户的channel，所以用户的会话是不是应该通过缓存共享，而不是内存呢

**Comment by LUCKYZHOUSTAR** [comment]
并且放到内存中，down机后，影响该设备上的所有用户
   public void sendMsg(SendMsgReqVO sendMsgReqVO) {
        NioSocketChannel socketChannel = SessionSocketHolder.get(sendMsgReqVO.getUserId());

        if (null == socketChannel) {
            throw new NullPointerException("客户端[" + sendMsgReqVO.getUserId() + "]不在线！");
        }
        CIMRequestProto.CIMReqProtocol protocol = CIMRequestProto.CIMReqProtocol.newBuilder()
                .setRequestId(sendMsgReqVO.getUserId())
                .setReqMsg(sendMsgReqVO.getMsg())
                .setType(Constants.CommandType.MSG)
                .build();

        ChannelFuture future = socketChannel.writeAndFlush(protocol);
        future.addListener((ChannelFutureListener) channelFuture ->
                LOGGER.info("服务端手动发送 Google Protocol 成功={}", sendMsgReqVO.toString()));
    }

**Comment by LUCKYZHOUSTAR** [comment]
该问题关闭了，再路由层看到了用户与server之间的匹配关系，不好意思

**Comment by crossoverJie** [comment]
> 该问题关闭了，再路由层看到了用户与server之间的匹配关系，不好意思

我正准备回复🤣
