### ISSUE TITLE
客户端重连服务端的定时任务一直执行，没有关闭重连任务

### ISSUE THREAD

**Issue by sdisk** [crossoverJie/cim#50]
**Bug 描述**
客户端重连服务端的定时任务一直执行，没有关闭重连任务

**代码**
   @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {

        if (shutDownMsg == null){
            shutDownMsg = SpringBeanFactory.getBean(ShutDownMsg.class) ;
        }

        //用户主动退出，不执行重连逻辑
        if (shutDownMsg.checkStatus()){
            return;
        }

        if (scheduledExecutorService == null){
            scheduledExecutorService = SpringBeanFactory.getBean("scheduledTask",ScheduledExecutorService.class) ;
        }
        LOGGER.info("客户端断开了，重新连接！");
        // TODO: 2019-01-22 后期可以改为不用定时任务，连上后就关闭任务 节省性能。
        scheduledExecutorService.scheduleAtFixedRate(new ReConnectJob(ctx),0,10, TimeUnit.SECONDS) ;
    }

**Comment by crossoverJie** [comment]
当失败次数达到上限后会自动退出，这个逻辑没有触发嘛？

**Comment by sdisk** [comment]
public void reconnect() throws Exception {
        if (channel != null && channel.isActive()) {
            return;
        }
        //首先清除路由信息，下线
        routeRequest.offLine();

        LOGGER.info("开始重连。。");
        start();
        LOGGER.info("重连成功！！");
    }
重连任务中如果重连成功了  channel.isActive()，就return了， 没有关闭任务。

**Comment by crossoverJie** [comment]
`// TODO: 2019-01-22 后期可以改为不用定时任务，连上后就关闭任务 节省性能。`

TODO 有写，任务目前没有关闭，不影响使用，后期会优化。

**Comment by sdisk** [comment]
额，那如果一个服务端挂了，客户端进行重连操作会重新通过路由进行重新登录操作
`   String server = routeHandle.routeServer(serverCache.getAll(),String.valueOf(loginReqVO.getUserId()));
`
如果使用一致性hash策略
`
 public String process(List<String> values,String key){

        for (String value : values) {
            add(hash(value), value);
        }
        sort();

        return getFirstNodeValue(key) ;
    }
`
这个process方法首先应该先清空map吧，不然还有无效的服务器信息在里面，这个map也只会越来越大

**Comment by crossoverJie** [comment]
> 而且这个map也只会越来越大

嗯，这是一个问题。

不过不建议在这里清空 `map`,这样还得考虑并发加锁的问题。

建议将这个 `map` 放在这里作为局部变量传递到后续的方法中，可以高效避免并发问题。

```java
    public String process(List<String> values,String key){
		Map value = new xx();
        for (String value : values) {
            add(value,hash(value), value);
        }
        sort(value);

        return getFirstNodeValue(value,key) ;
    }
```
