### ISSUE TITLE
真AI[滑稽]，手动[狗头]

### ISSUE THREAD

**Issue by xuxiake2017** [crossoverJie/cim#52]
![image](https://user-images.githubusercontent.com/26686948/64511630-4c572980-d317-11e9-9ffc-7eeaaee15660.png)

**Comment by DockerChen** [comment]
哈哈

**Comment by tuenli** [comment]
sabi------------------ 原始邮件 ------------------
发件人: "woniu"<notifications@github.com>
发送时间: 2019年9月22日(星期天) 中午11:41
收件人: "crossoverJie/cim"<cim@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [crossoverJie/cim] 真AI[滑稽]，手动[狗头] (#52)



&#x54C8;&#x54C8;
 
&mdash;
