### ISSUE TITLE
我看了你在51cto里面得关于im的集群的实现方案，不知道你们有没有微信交流群或者其他在线交流的方式

### ISSUE THREAD

**Issue by yuyu414** [crossoverJie/cim#54]
我看了你在51cto里面得关于im的集群的实现方案，不知道你们有没有微信交流群或者其他在线交流的方式，做了好几年的java了最近在做一个即时通讯的聊天软件，倒也开发出来了，只是不知道这其中的某些实现方案是否是最优的或者是业界先进的? 所以想进去和大家交流一些想法,如果有请把微信群，QQ，钉钉拉我一下，谢谢！我微信classmisschen，不胜感激

**Comment by crossoverJie** [comment]
请加我微信 chycjj
