### ISSUE TITLE
如果因服务器崩溃导致login-status里的对应的账号没有删除掉，会不会导致用户重连报账号已登录

### ISSUE THREAD

**Issue by nju-Nicko** [crossoverJie/cim#69]
如题，目前用户的登录信息保存在login-status里，
![image](https://user-images.githubusercontent.com/7032962/68096581-952cf800-feec-11e9-919b-73aadff91f0e.png)
可以看到这个k-v的ttl是-1，也就是没有设置失效时间。如果服务器崩溃导致没能正常清理这个login-status里的数据的话，客户端reconnect岂不是会报用户已登录了。
这边的高可靠性是否有考虑过。

**Comment by caydenprivate** [comment]
的确会有这个问题，目前只能是手动清除redis数据了

**Comment by crossoverJie** [comment]
@nju-Nicko @caydenprivate 

1. 如果 `server` 只有一个节点，当服务器宕机或者网络不通时：客户端会执行**下线**和重连，但现在已经没有可以提供的服务了，所以客户端会自动关闭。

由于会调用下线接口，所有当服务可用时再启动客户端便会登录成功及创建连接。

2. 如果 `server` 有多个节点，也会下线及重新选择一个可用节点创建连接。

所以不会出现这个问题，相关代码：

https://github.com/crossoverJie/cim/blob/e6ea441de19f1a90c30bc5c93d1caa940b88c3c5/cim-client/src/main/java/com/crossoverjie/cim/client/handle/CIMClientHandle.java#L95

https://github.com/crossoverJie/cim/blob/e6ea441de19f1a90c30bc5c93d1caa940b88c3c5/cim-client/src/main/java/com/crossoverjie/cim/client/client/CIMClient.java#L217
