### ISSUE TITLE
用treemap做一致性哈希环，需要设置长度吗

### ISSUE THREAD

**Issue by ffyyhh995511** [crossoverJie/cim#73]
请问一下，看了一些文章，说哈希是环形的，有固定长度，看了你的common模块的treemap，你是一个个去比较大小，相邻的就是命中的节点，请问这里是可以改进的还是本来就这样就行了

**Comment by crossoverJie** [comment]
理论上来说一致性 hash 算法存在的槽位为 `2^32`，但在实际使用时肯定不会直接初始化这么大一个数组，和常规的容器一样都是容器快满的时候再进行扩容。
