### ISSUE TITLE
IndexController @Autowired report an error

### ISSUE THREAD

**Issue by abyssal0** [crossoverJie/cim#75]
Could not autowire. There is more than one bean of 'CounterService' type.
Beans:
counterService   (MetricRepositoryAutoConfiguration.class) counterService   (MetricRepositoryAutoConfiguration.class)

**Comment by crossoverJie** [comment]
我本地无法复现，看报错是存在了两个 bean，可以尝试将这行代码注释试试。

https://github.com/crossoverJie/cim/blob/83150ff39a31dd22fdda1f23e132cef022caa1b5/cim-server/src/main/java/com/crossoverjie/cim/server/controller/IndexController.java#L37
