### ISSUE TITLE
关于 Client Login 的问题

### ISSUE THREAD

**Issue by 46094570** [crossoverJie/cim#8]
在 client login 的时候，userLogin 方法会向 Route 发送验证登录信息。让人疑惑的事，Route 去 Redis 中检查这个 client 是否存在，在接下来的 if 判断语句中，如果这个 client 不存在，返回的居然是已登录 - -!  这里非常不明白，是个 bug 吗

**Comment by crossoverJie** [comment]
没太懂什么意思。

https://github.com/crossoverJie/cim/blob/b6608ad4c6ede722771a87d36410a6e9645583da/cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java#L72-L92

不存在是返回的 `false`。

**Comment by 46094570** [comment]
> 没太懂什么意思。
> 
> [cim/cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java](https://github.com/crossoverJie/cim/blob/b6608ad4c6ede722771a87d36410a6e9645583da/cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java#L72-L92)
> 
> Lines 72 to 92 in [b6608ad](/crossoverJie/cim/commit/b6608ad4c6ede722771a87d36410a6e9645583da)
> 
>  public boolean login(LoginReqVO loginReqVO) throws Exception { 
>      //再去Redis里查询 
>      String key = ACCOUNT_PREFIX + loginReqVO.getUserId(); 
>      String userName = redisTemplate.opsForValue().get(key); 
>      if (null == userName) { 
>          return false; 
>      } 
>   
>      if (!userName.equals(loginReqVO.getUserName())) { 
>          return false; 
>      } 
>   
>      //登录成功，保存登录状态 
>      boolean status = userInfoCacheService.saveAndCheckUserLoginStatus(loginReqVO.getUserId()); 
>      if (status == false){ 
>          //重复登录 
>          return false; 
>      } 
>   
>      return true; 
>  } 
> 不存在是返回的 `false`。

你看这里啊，用前缀+userId去查询redis，如果从来没登录过（一次都没有，或者第一次启动系统），那就是空。然后在com.crossoverjie.cim.route.controller.RouteController#login 这个方法中，if(login) 才执行保存路由信息，不然的话就是返回说已经重复登录了。这种情况下逻辑不是有点问题么，我从来没有登录过，为何结果要返回给我说账号已登录？

**Comment by crossoverJie** [comment]
@46094570 

我懂你意思了，就是 `userID+userName` 不匹配的话还是返回的重复登录吧？

这是因为之前没考虑重复登录的事就只用了 `boolean` 来保存状态，所以只有两种值。

后面优化为一个枚举提示`登录信息不匹配`即可。

**Comment by xuegangliu** [comment]
1. 第一次登录redis里没有用户，应该登录成功
1. 第二次登录在redis查询出用户应该显示重复登录吧

**Comment by huxudong** [comment]
我也遇到这个问题了，启动client提示用户不存在。

**Comment by huxudong** [comment]
我感觉大家的困惑是，如何才能登录呢？

**Comment by crossoverJie** [comment]
@huxudong 你用的是我搭的公网服务嘛？

演示环境里目前没有 `zhangsan1` 这个账号，**只是提示有问题**。



> 我感觉大家的困惑是，如何才能登录呢？

`userId + userName` 在 `Redis` 能匹配并且没有其他人先登录即可登录；具体请看详细设计：

https://crossoverjie.top/2019/01/02/netty/cim01-started/#%E7%99%BB%E5%BD%95

**Comment by huxudong** [comment]
> @huxudong 你用的是我搭的公网服务嘛？
> 
> 演示环境里目前没有 `zhangsan1` 这个账号，**只是提示有问题**。
> 
> > 我感觉大家的困惑是，如何才能登录呢？
> 
> `userId + userName` 在 `Redis` 能匹配并且没有其他人先登录即可登录；具体请看详细设计：
> 
> https://crossoverjie.top/2019/01/02/netty/cim01-started/#%E7%99%BB%E5%BD%95

> 我用的自己的zk、redis

**Comment by crossoverJie** [comment]
> 我用的自己的zk、redis

那就查看自己的 `Redis` 里是否有这个用户，和你的 `userID+userName` 是否匹配（ps:登录的前提是要注册）。

> `userId + userName` 在 `Redis` 能匹配并且没有其他人先登录即可登录；

**Comment by huxudong** [comment]
> > 我用的自己的zk、redis
> 
> 那就查看自己的 `Redis` 里是否有这个用户，和你的 `userID+userName` 是否匹配（ps:登录的前提是要注册）。
> 
> > `userId + userName` 在 `Redis` 能匹配并且没有其他人先登录即可登录；



@crossoverJie 
> ok了，谢谢，我用postman注册了一下，然后配置到client，启动了一下。

**Comment by crossoverJie** [comment]
@huxudong 

这种小问题用 `issue` 不太好，可以加我微信 Y2h5Y2pq(base64) 我拉你进内测群，方便沟通。

**Comment by xiaozi0lei** [comment]
不知道我这个文档是否能解决大家的问题，其实很多人应该都是本地跑环境，可能存在redis没有账号缓存，导致不能登录，如图：
![image](https://user-images.githubusercontent.com/1046139/50673306-d841e480-1017-11e9-9e16-5fa52efd3e3b.png)
可以参考一下这个 PR  #11  会有点帮助，我本地跑起来了

**Comment by crossoverJie** [comment]
fixed.

![image](https://user-images.githubusercontent.com/15684156/51068764-bc64c100-165d-11e9-95ae-460ff1c8e027.png)
![image](https://user-images.githubusercontent.com/15684156/51068775-ce466400-165d-11e9-9167-88ee9aece25d.png)
