### ISSUE TITLE
1.客户端连接路由策略有文章介绍吗，没找到代码呢

### ISSUE THREAD

**Issue by TangYuFan** [crossoverJie/cim#80]

**Comment by crossoverJie** [comment]
https://crossoverjie.top/2019/03/01/algorithm/consistent-hash/

这里有相关介绍。

**Comment by TangYuFan** [comment]
好的我先研究一下，感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "crossoverJie"<notifications@github.com&gt;; 
发送时间: 2020年3月16日(星期一) 下午4:57
收件人: "crossoverJie/cim"<cim@noreply.github.com&gt;; 
抄送: "TangYuFan"<995435702@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crossoverJie/cim] 1.客户端连接路由策略有文章介绍吗，没找到代码呢 (#80)





 
Closed #80.
