### ISSUE TITLE
启动客户端只显示了一行错误就退出了

### ISSUE THREAD

**Issue by jdkYang** [crossoverJie/cim#83]
[2020-03-29 10:03:13] zhangsan$ 登录信息不匹配！

Process finished with exit code 255

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/38898113/77838247-bc8aa700-71a4-11ea-9fe7-bf76f15728c8.png">

请问这是怎么回事啊，谢谢大佬解答

**Comment by lifeKing** [comment]
你没注册用户，需要先注册才能启动客户端登录

发自我的iPhone

**Comment by jdkYang** [comment]
您好，我看到怎么注册了，谢谢您，非常感激，打扰您了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryne.D <notifications@github.com&gt;
发送时间: 2020年3月29日 10:10
收件人: crossoverJie/cim <cim@noreply.github.com&gt;
抄送: jdkYang <940604949@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[crossoverJie/cim] 启动客户端只显示了一行错误就退出了 (#83)





 你没注册用户，需要先注册才能启动客户端登录
 
 发自我的iPhone
 
 &gt; 在 2020年3月29日，10:06，jdkYang <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; [2020-03-29 10:03:13] zhangsan$ 登录信息不匹配！
 &gt; 
 &gt; Process finished with exit code 255
 &gt; 
 &gt; 
 &gt; 
 &gt; 请问这是怎么回事啊，谢谢大佬解答
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jdkYang** [comment]
您好，非常感激您的回答，请问怎么注册用户呢😢，小白感激您的回答因为在github上没找到注册用户的说明，谢谢您。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryne.D <notifications@github.com&gt;
发送时间: 2020年3月29日 10:10
收件人: crossoverJie/cim <cim@noreply.github.com&gt;
抄送: jdkYang <940604949@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[crossoverJie/cim] 启动客户端只显示了一行错误就退出了 (#83)





 你没注册用户，需要先注册才能启动客户端登录
 
 发自我的iPhone
 
 &gt; 在 2020年3月29日，10:06，jdkYang <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; [2020-03-29 10:03:13] zhangsan$ 登录信息不匹配！
 &gt; 
 &gt; Process finished with exit code 255
 &gt; 
 &gt; 
 &gt; 
 &gt; 请问这是怎么回事啊，谢谢大佬解答
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
