### ISSUE TITLE
提一个消息走队列的优化方案

### ISSUE THREAD

**Issue by hiwjcn** [crossoverJie/cim#92]
每个server实例启动后
``` c#
redis_list.pop("server_id")
或者
redis_pubsub.sub("server_id",msg=>{})
```
有客户端链接后把user_id->server_id写入redis。
再server端缓存当前server所有链接的用户的user_id->server_id和group_id->server_id。
(client链接有变动就刷新，或者定时全量刷新)

这样点对点发消息只要
``` c#
var server_id=server_client_list.get("user_id")
redis_list.push(server_id,"msg")
或者
redis_pubsub.publish(server_id,"msg")
```

**Comment by hiwjcn** [comment]
另外user->server存储再redis里
每次用scan去拉效率是不是也不太好

**Comment by crossoverJie** [comment]
这是要优化什么问题呢？没怎么看懂。

**Comment by hiwjcn** [comment]
比http效率高，
不需要zookeeper.
服务器之间耦合小

**Comment by crossoverJie** [comment]
`Zookeeper` 在这里是存放 `server` 节点信息的，不需要 `Zookeeper` 那是把信息存放在 Redis 里嘛？

这个和 `http` 有啥关系呢？

**Comment by hiwjcn** [comment]
我实现了一个分布式的聊天服务，只用到了redis。

server节点启动会生成一个key，然后再redis里subscribe这个key。

用户链接到这个节点后会把用户id对应的server key和设备信息注册到redis的hash里。



点对点发消息的时候先去redis hash里通过userid获取server key，然后把消息publish到这个key

**Comment by hiwjcn** [comment]
pubsub可以用list替代，广播可以用pubsub。这样相比http耦合度会比较小，节点和节点之间可以跨网络

**Comment by crossoverJie** [comment]
我大概明白你的意思了，等于是利用 Redis 的 pub/sub 实现的消息发送，点对点的时候客户端A 向客户端B 所订阅的 Channel 中发消息，这样实现的嘛？

如果是这样的话我觉得有几个问题：
- 用户在登录之后选择具体的服务节点时如何做到及时的服务自动发现及下线，这也是我使用 Zookeeper 的原因。
- 基于 Redis 的消息推送会将 Redis 暴露在外网，我觉得这并不太合适；会有安全和带宽的问题。
- 再一个是我的本意是利用自定义协议的 TCP 双工长连接的特性来做消息的下发和推送，虽然 Redis 的 pub/sub 本质也是 TCP，但和我的初衷有点背道而驰了。

**Comment by hiwjcn** [comment]
redis只是服务器节点之间的消息传递 服务器和client还是你自己定义的长链接
